services:
    ezpublish_legacy.debug.templates_collector:
        class: eZ\Bundle\EzPublishLegacyBundle\Collector\LegacyTemplatesCollector
        public: false
        arguments: ["@ezpublish_legacy.kernel"]
        tags:
            -
                name: ezpublish_data_collector
                panelTemplate: "@EzPublishLegacy/Profiler/templates/panel.html.twig"
                toolbarTemplate: "@EzPublishLegacy/Profiler/templates/toolbar.html.twig"
