services:
    ezpublish_legacy.image_alias.cleaner:
        class: eZ\Publish\Core\MVC\Legacy\Image\AliasCleaner
        arguments:
            - "@ezpublish.image_alias.imagine.alias_cleaner"
            - "@ezpublish.core.io.image_fieldtype.legacy_url_redecorator"
        lazy: true
        public: false
