services:
    ezpublish_legacy.security.voter.core:
        class: eZ\Publish\Core\MVC\Legacy\Security\Voter\VoterDecorator
        decorates: ezpublish.security.voter.core
        public: false
        arguments: ["@ezpublish_legacy.security.voter.core.inner", "@ezpublish_legacy.kernel"]

    ezpublish_legacy.security.voter.value_object:
        class: eZ\Publish\Core\MVC\Legacy\Security\Voter\VoterDecorator
        decorates: ezpublish.security.voter.value_object
        public: false
        arguments: ["@ezpublish_legacy.security.voter.value_object.inner", "@ezpublish_legacy.kernel"]

    ezpublish_legacy.security.login_cleanup_listener:
        class: eZ\Publish\Core\MVC\Legacy\Security\Firewall\LoginCleanupListener
        public: false
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.security_mapper:
        class: eZ\Bundle\EzPublishLegacyBundle\LegacyMapper\Security
        public: false
        arguments: ["@ezpublish.api.repository", "@ezpublish.config.resolver", "@security.token_storage", "@security.authorization_checker"]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.security.sso_firewall_listener:
        class: eZ\Publish\Core\MVC\Legacy\Security\Firewall\SSOListener
        public: false
        abstract: true
        arguments:
            - "@security.token_storage"
            - "@security.authentication.manager"
            - ~     # Will be replaced at compile time by the security factory to be the right user provider
            - "@?logger"
            - "@?event_dispatcher"
        calls:
            - [setLegacyKernelClosure, ["@ezpublish_legacy.kernel"]]
            - [setUserService, ["@ezpublish.api.service.user"]]
