parameters:
    ezpublish_legacy.view_decorator.options:
        viewbaseLayout: "%ezpublish.content_view.viewbase_layout%"
        contentBlockName: "%ezpublish.content_view.content_block_name%"

services:
    ezpublish_legacy.view_provider:
        class: eZ\Publish\Core\MVC\Legacy\View\Provider
        arguments: ["@ezpublish_legacy.kernel", "@ezpublish_legacy.view_decorator", "@ezpublish_legacy.templating.legacy_helper", "@?logger"]
        abstract: true
        public: false

    ezpublish_legacy.content_view_provider:
        class: eZ\Publish\Core\MVC\Legacy\View\Provider\Content
        parent: ezpublish_legacy.view_provider
        public: false
        tags:
            - {name: ezpublish.view_provider, type: 'eZ\Publish\Core\MVC\Symfony\View\ContentView', priority: 4}

    ezpublish_legacy.location_view_provider:
        class: eZ\Publish\Core\MVC\Legacy\View\Provider\Location
        parent: ezpublish_legacy.view_provider
        public: false
        calls:
            # Injecting the request, in non strict mode ("=") avoiding this service to be forced in request scope.
            - [setRequestStack, ["@request_stack"]]
        tags:
            # Location view provider must have priority higher than content view provider to be able
            # to match the location first, in case it exists in the view
            - {name: ezpublish.view_provider, type: 'eZ\Publish\Core\MVC\Symfony\View\ContentView', priority: 5}

    ezpublish_legacy.block_view_provider:
        class: eZ\Publish\Core\MVC\Legacy\View\Provider\Block
        parent: ezpublish_legacy.view_provider
        public: false
        calls:
            - [setPageService, ["@ezpublish.fieldType.ezpage.pageService"]]
        tags:
            - {name: ezpublish.view_provider, type: 'eZ\Publish\Core\MVC\Symfony\View\BlockView', priority: 5}

    ezpublish_legacy.view_decorator.twig:
        class: eZ\Publish\Core\MVC\Legacy\View\TwigContentViewLayoutDecorator
        public: false
        arguments: ["@twig", "%ezpublish_legacy.view_decorator.options%", "@ezpublish.config.resolver"]

    ezpublish_legacy.view_decorator:
        alias: ezpublish_legacy.view_decorator.twig
        public: false
