parameters:
    ezpublish_legacy.switchable_http_cache_purger.class: eZ\Bundle\EzPublishLegacyBundle\Cache\LegacySwitchableHttpCachePurger

services:
    ezpublish_legacy.switchable_http_cache_purger:
        class: "%ezpublish_legacy.switchable_http_cache_purger.class%"
        arguments: ["@ezpublish.http_cache.purger"]
